rm(list=ls())
source('KS_stats.R')
source('ars.R')

test_that("Empirical distribution matches", {

  cat("Testing normal distribution now:")
  g <- function(x) dnorm(x,0,1)
  x <- ars(g,20000,-10,10,batchsize=100)
  KS <- KS_norm(x,0,1)
  expect_that( KS, equals(0, tolerance  = 0.05))
  cat("Estimate of KS statistic: ", KS)
  cat("\n\n")

  cat("Testing gamma distribution now:")
  g <- function(x) dgamma(x,2,2)
  x <- ars(g,20000,0,10,batchsize=100)
  KS <- KS_gamma(x,2,2)
  expect_that(KS, equals(0, tolerance  = 0.02))
  cat("Estimate of KS statistic: ", KS)
  cat("\n\n")

  cat("Testing uniform distribution now:")
  g <- function(x) dunif(x,0,1)
  x <- ars(g,20000,0,1,batchsize=100)
  KS <- KS_unif(x,0,1)
  expect_that(KS, equals(0, tolerance  = 0.02))
  cat("Estimate of KS statistic: ", KS)
  cat("\n\n")

  cat("Testing beta distribution now:")
  g <- function(x) dbeta(x,2,2)
  x <- ars(g,20000,0,1,batchsize=100)
  KS <- KS_beta(x,2,2)
  expect_that(KS, equals(0, tolerance  = 0.02))
  cat("Estimate of KS statistic: ", KS)
  cat("\n\n")

  cat("Testing chi-square distribution now:")
  g <- function(x) dchisq(x,3)
  x <- ars(g,20000,0,10,batchsize=100)
  KS <-  KS_chi(x,3)
  expect_that(KS, equals(0, tolerance  = 0.02))
  cat("Estimate of KS statistic: ", KS)
  cat("\n\n")
  
  print("Testing exponential distribution now:")
  g <- function(x) dexp(x,2)
  x <- ars(g,20000,0,3,batchsize=100)
  KS <- KS_exp(x,2)
  expect_that(KS, equals(0, tolerance  = 0.02))
  cat("Estimate of KS statistic: ", KS)
  cat("\n\n")
  
  cat("Testing weibull distribution now:")
  g <- function(x) dweibull(x,2,1)
  x <- ars(g,20000,0,3,batchsize=100)
  KS <- KS_weibull(x,2,1)
  expect_that(KS, equals(0, tolerance  = 0.02))
  cat("Estimate of KS statistic: ", KS)

})
