library(testthat)
library(ars)
library(numDeriv)
source('KS_stats.R')
source('function_for_test.R')
g<-dnorm
test_that("Empirical distribution matches", {

  print("Testing normal distribution now:")
  g <- function(x) dnorm(x,0,1)
  x <- ars(g,5000,-10,10,batchsize=100)
  KS <- KS_norm(x,0,1)
  print(expect_that( KS, equals(0, tolerance  = 0.05)))
  print("Estimate of KS Statistic:")
  print(KS)
  cat("\n\n")

  print("Testing gamma distribution now:")
  g <- function(x) dgamma(x,2,2)
  x <- ars(g,5000,0,10,batchsize=100)
  KS <- KS_gamma(x,2,2)
  print(expect_that( KS, equals(0, tolerance  = 0.05)))
  print("Estimate of KS Statistic:")
  print(KS)
  cat("\n\n")

  print("Testing uniform distribution now:")
  g <- function(x) dunif(x,0,1)
  x <- ars(g,5000,0,1,batchsize=100)
  KS <- KS_unif(x,0,1)
  print(expect_that( KS, equals(0, tolerance  = 0.05)))
  print("Estimate of KS Statistic:")
  print(KS)
  cat("\n\n")

  print("Testing beta distribution now:")
  g <- function(x) dbeta(x,2,2)
  x <- ars(g,5000,0.01,0.99,batchsize=100)
  KS <- KS_beta(x,2,2)
  print(expect_that( KS, equals(0, tolerance  = 0.05)))
  print("Estimate of KS Statistic:")
  print(KS)
  cat("\n\n")

  print("Testing chi-square distribution now:")
  g <- function(x) dchisq(x,3)
  x <- ars(g,5000,0.01,10,batchsize=1000)
  KS <- KS_chi(x,3)
  print(expect_that( KS, equals(0, tolerance  = 0.05)))
  print("Estimate of KS Statistic:")
  print(KS)
  cat("\n\n")

  print("Testing exponential distribution now:")
  g <- function(x) dexp(x,2)
  x <- ars(g,20000,0,3,batchsize=100)
  KS <- KS_exp(x,2)
  print(expect_that(KS, equals(0, tolerance  = 0.02)))
  print("Estimate of KS Statistic:")
  print(KS)
  cat("\n\n")

  cat("Testing weibull distribution now:")
  g <- function(x) dweibull(x,2,1)
  x <- ars(g,20000,0,3,batchsize=100)
  KS <- KS_weibull(x,2,1)
  print(expect_that(KS, equals(0, tolerance  = 0.02)))
  print("Estimate of KS Statistic:")
  print(KS)
})

